name: Deploy

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Publish frontend
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: vracine/frontend
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_semver: true

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Update Dockerrun.aws.json with tag
        run: sed -i "s|TAG_PLACEHOLDER|${{ github.ref_name }}|" Dockerrun.aws.json

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*' -x 'Dockerfile' -x 'Dockerfile.dev'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: frontend
          environment_name: Frontend-env
          region: us-east-2
          version_label: ${{ github.ref_name }}
          deployment_package: deploy.zip
